services:
  webui:
    build:
      context: ./webui
    ports:
      - ${WEBUI_PORT-7860}:7860
    volumes:
      - ./webui/data:/home/ubuntu/stable-diffusion-webui/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
